const characterActionTypes = {
  FETCH_CHARACTER_START: "FETCH_CHARACTER_START",
  FETCH_CHARACTER_SUCCESS: "FETCH_CHARACTER_SUCCESS",
  FETCH_CHARACTER_FAILURE: "FETCH_CHARACTER_FAILURE",
  FETCH_CHARACTERID_START: "FETCH_CHARACTERID_START",
  FETCH_CHARACTERID_SUCCESS: "FETCH_CHARACTERID_SUCCESS",
  FETCH_CHARACTERID_FAILURE: "FETCH_CHARACTERID_FAILURE",
  SEARCH_CHARACTER_START: "SEARCH_CHARACTER_START",
  SEARCH_CHARACTER_SUCCESS: "SEARCH_CHARACTER_SUCCESS",
  SEARCH_CHARACTER_FAILURE: "SEARCH_CHARACTER_FAILURE",
  FILTER_CHARACTER_START: "FILTER_CHARACTER_START",
  FILTER_CHARACTER_SUCCESS: "FILTER_CHARACTER_SUCCESS",
  FILTER_CHARACTER_FAILURE: "FILTER_CHARACTER_FAILURE",
  FETCH_EPISODE_START: "FETCH_EPISODE_START",
  FETCH_EPISODE_SUCCESS: "FETCH_EPISODE_SUCCESS",
  FETCH_EPISODE_FAILURE: "FETCH_EPISODE_FAILURE",
};

export default characterActionTypes;
